### ISSUE TITLE
AttributeError: 'Session' object has no attribute 'scalars'

### ISSUE THREAD

**Issue by andypinxinliu** [MacHu-GWU/uszipcode-project#65]
It seems like it does not work on python 3.9.7 on my mac.

The following is the error message I have got:

Exception ignored in: <function SearchEngine.__del__ at 0x7f78716c7430>
Traceback (most recent call last):
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/uszipcode/search.py", line 196, in __del__
    self.close()
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/uszipcode/search.py", line 202, in close
    self.ses.close()
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1757, in close
    self._close_impl(invalidate=False)
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1799, in _close_impl
    transaction.close(invalidate)
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 923, in close
    transaction.close()
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2287, in close
    self._do_close()
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2503, in _do_close
    self._close_impl()
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2489, in _close_impl
    self._connection_rollback_impl()
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2481, in _connection_rollback_impl
    self.connection._rollback_impl()
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 960, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 958, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/Users/pinxinliu/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
(Background on this error at: https://sqlalche.me/e/14/f405)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/zy/ck0fl6_j03b7vb1tgyc2zy1m0000gn/T/ipykernel_6703/593555264.py in <module>
      1 from uszipcode import SearchEngine
      2 search = SearchEngine(simple_or_comprehensive=SearchEngine.SimpleOrComprehensiveArgEnum.simple)
----> 3 res = search.by_city_and_state("cicago", "il", returns=999)
      4 print(res[0])

~/opt/anaconda3/lib/python3.9/site-packages/uszipcode/search.py in by_city_and_state(self, city, state, zipcode_type, sort_by, ascending, returns)
    800         My engine use fuzzy match and guess what is the state you want.
    801         """
--> 802         return self.query(
    803             city=city,
    804             state=state,

~/opt/anaconda3/lib/python3.9/site-packages/uszipcode/search.py in query(self, zipcode, prefix, pattern, city, state, lat, lng, radius, population_lower, population_upper, population_density_lower, population_density_upper, land_area_in_sqmi_lower, land_area_in_sqmi_upper, water_area_in_sqmi_lower, water_area_in_sqmi_upper, housing_units_lower, housing_units_upper, occupied_housing_units_lower, occupied_housing_units_upper, median_home_value_lower, median_home_value_upper, median_household_income_lower, median_household_income_upper, zipcode_type, sort_by, ascending, returns)
    688                 stmt = stmt.limit(returns)
    689 
--> 690             return self.ses.scalars(stmt).all()
    691 
    692     def by_zipcode(

AttributeError: 'Session' object has no attribute 'scalars'
